### ISSUE TITLE
POST with FormData data turns it into JSON

### ISSUE THREAD

**Issue by rgalanakis** [gre/qajax#13]
Trying to POST with a `FormData` instance gives the request a header of `application/json`. It should not add a header, and allow XHR to serialize FormData and add a `multipart/form-data` header.

Also, really nice lib :)

**Comment by panzerdp** [comment]
Having the same problem.

**Comment by gre** [comment]
Hi,
@panzerdp which version of Qajax was you testing with? This should be fixed in 1.3.0

You can now give a FormData instance in `data` field

Usage example:
https://github.com/gre/diaporama-maker/blob/a0f19aa8b7db5c8939a8a0591d2022d7ee4ea283/client/index.js#L91-L102

**Comment by panzerdp** [comment]
Hi @gre, thanks for your quick answer.
I'm using the latest 1.3.0 version.
I was posting using a JSON object, and probably because of that it sent directly json string. I think it will work correct with FormData object, thanks for clarification.
But the way jQuery post method works is more efficient. Event sending plain objects, it transforms it to form data. If I have a lot of params to send and transforming to FormData adds an unneeded step :).
Thanks.

**Comment by gre** [comment]
How would it guess if user want to send a JSON or a FormData ? I think this would introduce complex logic whereas the user could explicitely provide it.

jQuery ajax method reconciliates a lot of parameters, and the philosophy of Qajax is to stay as minimalist as possible on top of XMLHttpRequest and try not to hide to much this API. So what it fundamentally do right now is to "Promisify" its API and remove a bit the "mutable" style of the XHR api.
I've even been thinking that the "getJSON" utility might not be in the library (but since it's a common use-case I've kept it in..)

So at least it is now possible to send a FormData (that can includes File too), I'm not sure I want to go deeper following that path.

**Comment by panzerdp** [comment]
@gre I agree with you about the simplicity. You can add an additional parameter how it is necessary to send data.

**Comment by rgalanakis** [comment]
I think `Qajax.objectToFormData` would be a welcome addition to the library- though I would definitely not want any magic happening in the actual XHR call. It could just be a helper and would remove some code that is probably rewritten for so many projects. I'm a big fan of minimalism myself but utilities like this don't really add complexity, IMO.

**Comment by gre** [comment]
`Qajax.objectToFormData` is a good idea yes. if any of you want to provide a PR. otherwise I might do it in some days
